import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Charles Hodgins - Personal Website",
  description: "Generated by create next app",
};

const sections = ["About", "Resume/CV", "Projects"];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href = 'Charles_Hodgins2.png' type="image/png"/>
        <meta name={metadata.title} content={metadata.description} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
