import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Charles Hodgins - Portfolio",
  description: "Generated by create next app",
};

const sections = ["About", "Resume/CV", "Projects"];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name={metadata.title} content={metadata.description} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <div className="main">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
