import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Charles Hodgins - Personal Website",
  description: "Generated by create next app",
};

const sections = ["Home", "Projects"];
const links = ["/", "/projects"];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Charles_Hodgins2.png" type="image/png" />
        <meta name={metadata.title} content={metadata.description} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar links={links} sections={sections} />
        <div className="main">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
